import { useState } from 'react';
import { ethers } from 'ethers';
import { ARC_RPC, ARC_RPC_FALLBACK, ARC_CHAIN_ID } from '../config';
import { sbInsert, sbSelect, sbUpdate, ls, lsSave, short, awaitReceipt, sendNotif } from '../config';

export function useInvoices({ address, signer, provider, setStatus, setLoading, setTxns, awardCashback, refreshBal, payId, setPayId, cleanErr, setShowConfirm }) {
  const[invPayer,setInvPayer]=useState('');
  const[invAmt,setInvAmt]=useState('');
  const[invDesc,setInvDesc]=useState('');
  const[invCtry,setInvCtry]=useState('');
  const[invId,setInvId]=useState('');
  const[payDet,setPayDet]=useState(null);

  const handleCreateInv=async()=>{if(!address){setStatus({type:'error',msg:'Connect your wallet first'});return;}if(!invPayer||!invAmt){setStatus({type:'error',msg:'Fill required fields'});return;}setLoading(true);setStatus({type:'info',msg:'Creating invoice...'});try{const id='0x'+Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b=>b.toString(16).padStart(2,'0')).join('');const invoice={id,creator:address,payer:invPayer.trim(),amount:invAmt,description:invDesc,country:invCtry,paid:false};await sbInsert('invoices',invoice);const saved=ls('arc_invoices',[]);lsSave('arc_invoices',[{...invoice,desc:invDesc,ts:Math.floor(Date.now()/1000)},...saved.slice(0,99)]);setInvId(id);setStatus({type:'success',msg:'Invoice created. Share the ID with your client.'});setInvPayer('');setInvAmt('');setInvDesc('');}catch(e){setStatus({type:'error',msg:'Failed: '+e.message});}finally{setLoading(false);}};

  const handlePayInv=async(inv)=>{setShowConfirm(false);if(!signer)return;setLoading(true);setStatus({type:'info',msg:'Processing payment...'});try{const value=ethers.parseUnits(inv.amount,18);let gasPrice;try{const rpcs=[ARC_RPC,ARC_RPC_FALLBACK].filter(Boolean);let feeData=null;for(const rpc of rpcs){try{const rp=new ethers.JsonRpcProvider(rpc,{name:'Arc Testnet',chainId:ARC_CHAIN_ID});feeData=await Promise.race([rp.getFeeData(),new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),4000))]);if(feeData)break;}catch{}}const fp=feeData?.gasPrice;gasPrice=(fp&&fp>0n)?fp:ethers.parseUnits('100','gwei');}catch{gasPrice=ethers.parseUnits('100','gwei');}const nonce=await provider.getTransactionCount(address,'pending');const tx=await signer.sendTransaction({to:inv.creator,value,gasPrice,nonce});await sbUpdate('invoices','id=eq.'+payId.trim(),{paid:true,paid_by:address,paid_tx:tx.hash});const rec={hash:tx.hash,recipient:inv.creator,amount:inv.amount,country:inv.country,timestamp:Math.floor(Date.now()/1000),status:'submitted',type:'invoice'};setTxns(prev=>{const u=[rec,...prev.slice(0,499)];lsSave('arc_txhistory_'+address,u);return u;});awaitReceipt(provider,tx.hash).then(receipt=>{const confirmed=receipt==null?'pending':receipt.status===1?'confirmed':'failed';if(confirmed==='confirmed'){awardCashback(tx.hash,parseFloat(inv.amount));sendNotif('Transaction Confirmed','Your USDC transfer was confirmed on Arc Testnet.');}setTxns(prev=>{const u=prev.map(t=>t.hash===tx.hash?{...t,status:confirmed}:t);lsSave('arc_txhistory_'+address,u);return u;});});setStatus({type:'success',msg:'Paid '+inv.amount+' USDC'});setPayId('');setPayDet(null);setTimeout(refreshBal,5000);}catch(e){setStatus({type:'error',msg:cleanErr(e)});}finally{setLoading(false);}};

  const handlePayInvReview=async(setConfirmData,setConfirmAction,setShowConfirm)=>{if(!signer||!payId){setStatus({type:'error',msg:'Enter invoice ID'});return;}setLoading(true);setStatus({type:'info',msg:'Looking up invoice...'});try{const rows=await sbSelect('invoices','id=eq.'+payId.trim()+'&select=*');if(!rows||rows.length===0){setStatus({type:'error',msg:'Invoice not found'});setLoading(false);return;}const inv=rows[0];if(inv.paid){setStatus({type:'error',msg:'This invoice has already been paid'});setLoading(false);return;}setPayDet({creator:inv.creator,amount:ethers.parseUnits(inv.amount,18),description:inv.description,country:inv.country,rawAmount:inv.amount});setStatus(null);setConfirmData({rows:[{k:'Invoice ID',v:payId.trim().slice(0,16)+'...'},{k:'Amount',v:inv.amount+' USDC'},{k:'Description',v:inv.description},{k:'To',v:short(inv.creator)},{k:'Est. Fee',v:'~0.0005 USDC',highlight:true}],confirmLabel:'Pay via Wallet'});setConfirmAction(()=>()=>handlePayInv(inv));setShowConfirm(true);}catch(e){setStatus({type:'error',msg:cleanErr(e)});}finally{setLoading(false);}};

  return { invPayer, setInvPayer, invAmt, setInvAmt, invDesc, setInvDesc, invCtry, setInvCtry, invId, setInvId, payDet, setPayDet, handleCreateInv, handlePayInv, handlePayInvReview };
}
