import { useState } from 'react';
import { ethers } from 'ethers';
import { ARC_RPC, ARC_RPC_FALLBACK, ARC_CHAIN_ID, ls, lsSave, awaitReceipt, sendNotif, short, CURRENCY } from '../config';

export function useSend({ signer, provider, address, walletName, rates, setStatus, setLoading, setTxns, awardCashback, refreshBal, cleanErr, setConfirmData, setConfirmAction, setShowConfirm }) {
  const[sendTo,setSendTo]=useState('');
  const[sendAmt,setSendAmt]=useState('');
  const[showScanner,setShowScanner]=useState(false);
  const[sendCtry,setSendCtry]=useState(()=>ls('arc_ctry',''));

  const handleSend=async()=>{setShowConfirm(false);if(!signer){setStatus({type:'error',msg:'Please reconnect your wallet to send transactions'});return;}if(!sendTo||!sendAmt)return;const amt=parseFloat(sendAmt);if(isNaN(amt)||amt<=0)return;setLoading(true);setStatus({type:'info',msg:'Sending USDC...'});try{const value=ethers.parseUnits(sendAmt,18);let gasPrice;try{const rpcs=[ARC_RPC,ARC_RPC_FALLBACK].filter(Boolean);let feeData=null;for(const rpc of rpcs){try{const rp=new ethers.JsonRpcProvider(rpc,{name:'Arc Testnet',chainId:ARC_CHAIN_ID});feeData=await Promise.race([rp.getFeeData(),new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),4000))]);if(feeData)break;}catch{}}const fp=feeData?.gasPrice;gasPrice=(fp&&fp>0n)?fp:ethers.parseUnits('100','gwei');}catch{gasPrice=ethers.parseUnits('100','gwei');}const nonce=await provider.getTransactionCount(address,'pending');const tx=await signer.sendTransaction({to:ethers.getAddress(sendTo.trim().toLowerCase()),value,gasPrice,nonce});const rec={id:tx.hash+'_'+sendTo,hash:tx.hash,recipient:sendTo,amount:amt,country:sendCtry,timestamp:Math.floor(Date.now()/1000),status:'pending'};setTxns(prev=>{const u=[rec,...prev.slice(0,499)];lsSave('arc_txhistory_'+address,u);return u;});setStatus({type:'success',msg:'Sent '+sendAmt+' USDC to '+short(sendTo)});setSendTo('');setSendAmt('');awaitReceipt(provider,tx.hash).then(receipt=>{const confirmed=receipt==null?'pending':receipt.status===1?'confirmed':'failed';if(confirmed==='confirmed'){awardCashback(tx.hash,amt);sendNotif('Transaction Confirmed','Your USDC transfer was confirmed on Arc Testnet.');}setTxns(prev=>{const u=prev.map(t=>t.hash===tx.hash?{...t,status:confirmed}:t);lsSave('arc_txhistory_'+address,u);return u;});});setTimeout(refreshBal,6000);}catch(e){setStatus({type:'error',msg:cleanErr(e)});}finally{setLoading(false);}};

  const handleSendReview=()=>{if(!sendTo||!sendAmt){setStatus({type:'error',msg:'Please fill all required fields'});return;}if(!ethers.isAddress(sendTo)&&!/^0x[0-9a-fA-F]{40}$/.test(sendTo)){setStatus({type:'error',msg:'Invalid recipient address'});return;}const amt=parseFloat(sendAmt);if(isNaN(amt)||amt<=0){setStatus({type:'error',msg:'Invalid amount'});return;}const rows=[{k:'You Send',v:sendAmt+' USDC'},{k:'Recipient',v:short(sendTo)}];if(sendCtry&&rates[CURRENCY[sendCtry]])rows.push({k:'They Receive',v:'~'+(amt*rates[CURRENCY[sendCtry]]).toLocaleString('en',{maximumFractionDigits:0})+' '+CURRENCY[sendCtry],highlight:true});rows.push({k:'Estimated Fee',v:'~0.0005 USDC',highlight:true},{k:'Network',v:'Arc Testnet'});if(walletName?.toLowerCase().includes('okx')){handleSend();}else{setConfirmData({rows,confirmLabel:'Send to Wallet'});setConfirmAction(()=>handleSend);setShowConfirm(true);}};

  return { sendTo, setSendTo, sendAmt, setSendAmt, showScanner, setShowScanner, sendCtry, setSendCtry, handleSend, handleSendReview };
}
